name: Clone, Build, and Commit

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        path: ./lesli.dev.repo/
        fetch-depth: '0'

    - name: Install dependencies w
      run: git clone https://github.com/LesliTech/lesli-vue.git

    - name: Install dependencies
      run: |
        ls
        cd lesli.dev.repo
        echo "inside repo"
        ls
        npm install

    - name: Build
      run: |
        cd lesli.dev.repo
        npm run build 

    - name: Configure Git
      run: |
        cd lesli.dev.repo
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Commit changes
      run: |
        cd lesli.dev.repo/build
        git init
        git add .
        git commit -m "Build and commit changes"
        git branch -m production
        git push origin production --force
