name: Clone, Build, and Commit

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        path: ./lesli.dev.repo/
        fetch-depth: '0'

    # Clone our custom actions
    - name: Checkout github actions repo
      uses: actions/checkout@v3
      with:
        ref: master
        path: ../
        fetch-depth: '0'
        repository: LesliTech/lesli-vue


    - name: Install dependencies
      run: |
        ls
        npm install

    - name: Build
      run: |
        npm run build 

    - name: Configure Git
      run: |
        cd lesli.dev.repo
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Commit changes
      run: |
        cd lesli.dev.repo/build
        git init
        git add .
        git commit -m "Build and commit changes"
        git branch -m production
        git push origin production --force
